#https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router 
[build]
  command = "CI=false && npm run build"
  publish = "build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 